### ISSUE TITLE
fix format script 

### ISSUE THREAD

**Issue by MarlonPassos-git** [radashi-org/radashi#115]
When I run `pnpm format`, nothing happens.
![image](https://github.com/user-attachments/assets/1dd62166-a5bd-40ff-8e7e-7f5b30e799d4)

When I investigate the `format.sh` file, an error occurs when the command is run.
![image](https://github.com/user-attachments/assets/6c626fb6-623a-418b-94d0-71aca90ac7bb)

Should that script work? I cannot find the glob script in `package.json`.

**Comment by aleclarson** [comment]
Hey, sorry about that! Apparently, `pnpm <command>` will check the global package store too, which is how `pnpm glob` worked for me but not you (i.e. I had `glob` installed globally).

Fixed in main 👍
