### ISSUE TITLE
debounce function

### ISSUE THREAD

**Issue by SingAurora** [radashi-org/radashi#164]
The debounce function is run at the end of the time window, there is no way to start running in the time window.

**Comment by MarlonPassos-git** [comment]
We have an open PR (#128) that addresses this by adding a `leading` option to the debounce function.

**Comment by MarlonPassos-git** [comment]
@SingAurora The PR was merged. Here's an example of how to use the `leading` option to trigger the function immediately on the first call:

```typescript
const genericFunction = () => {
  console.log("This function is called immediately when leading is true.");
};

const debouncedFunc = _.debounce({ delay: 5000, leading: true }, genericFunction);
```

**Comment by SingAurora** [comment]
Thank you so much for the great open source project




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "radashi-org/radashi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月15日(星期四) 中午1:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [radashi-org/radashi] debounce function (Issue #164)





 
@SingAurora The PR was merged. Here's an example of how to use the leading option to trigger the function immediately on the first call:
 const genericFunction = () =&gt; {   console.log("This function is called immediately when leading is true."); }; const debouncedFunc = _.debounce({ delay: 5000, leading: true }, genericFunction);
