### ISSUE TITLE
Add Mutex management functions - `exclusive`, `createMutex`

### ISSUE THREAD

**Issue by hugo082** [radashi-org/radashi#260]
Hi there 👋 Thanks for your contributions to this project.

Do you think it’s feasible to include utility function(s) to create a mutex object (similar to https://github.com/DirtyHairy/async-mutex)? I’m not sure if it aligns with the project’s ethos, maybe too much abstraction?

I would be happy to help in implementation :)

#### `exclusive` proposal
```ts
import * as _ from 'radashi'

const exclusiveFn = _.exclusive(async () => /* ... */)

// ran one by one
await _.all([
	exclusiveFn(),
	exclusiveFn()
])
```

#### `createMutex` proposal
```ts
import * as _ from 'radashi'

const mutex = _.createMutex()

// available properties / methods
const release = await mutex.acquire()
mutex.isLocked()

// ran one by one
await _.all([
	mutex.exclusive(async () => /* ... */),
	mutex.exclusive(async () => /* ... */),
])
```

**Comment by aleclarson** [comment]
We have a discussion that includes consideration of mutex functionality:
https://github.com/orgs/radashi-org/discussions/222

Could you copy your ideas over there? Thanks 👍
