### ISSUE TITLE
`group()` returns optional object values

### ISSUE THREAD

**Issue by aeharding** [radashi-org/radashi#287]
When I call `group`, it returns the object value type as `T | undefined`. However, this is not correct (and differs from other implementations, like `lodash.groupBy`).

Here is an example:

```ts
import * as _ from 'radashi'

const returnValues = _.group([1, 1.2, 1.3, 2], Math.floor);
const sum = Object.values(returnValues).reduce(
  (acc, curr) => acc + curr.length,
  0,
);

console.log(sum);
```

<img width="606" alt="image" src="https://github.com/user-attachments/assets/7f359989-d5f8-473a-9d18-6f4abfee95ea">

**Comment by aleclarson** [comment]
TypeScript cannot know at compile-time what values are in the array passed to `group`, so it cannot guarantee the existence of any particular group.

That said, using `exactOptionalPropertyTypes` *will* be a valid workaround if https://github.com/microsoft/TypeScript/issues/46969 is ever fixed.

**Comment by aeharding** [comment]
OK thanks, however I don't understand why it is not possible since lodash has the following signature and it works fine. Why not use that instead?

```ts
groupBy<T>(collection: List<T> | null | undefined, iteratee?: ValueIteratee<T>): Dictionary<T[]>;
```

With lodash, the following errors (`'value' is possibly 'null'.ts(18047)`) because `null` is in the array:

```ts
const returnValues = _.groupBy([null, 1.2, 1.3, 2]);
const sum = Object.values(returnValues).forEach((group) => {
  group.forEach((value) => {
    console.log(value + 1);
  });
});
```

but if I remove `null` it works:

```ts
const returnValues = _.groupBy([1.2, 1.3, 2]);
const sum = Object.values(returnValues).forEach((group) => {
  group.forEach((value) => {
    console.log(value + 1);
  });
});
```

**Comment by aleclarson** [comment]
Lodash's solution is only type-safe if you're using `Object.values` on the result.

A better solution is to extend our [`cluster`](https://github.com/radashi-org/radashi/blob/28c6efcf8b19227573c4f9a325ef47303c314827/src/array/cluster.ts) function to accept an optional "identity function" for cases where all you're doing is calling `Object.values` immediately after.

**Example**
```ts
cluster([null, 1.2, 1.3, 2], Math.floor)
// => [[null], [1.2, 1.3], [2]]
```

**Comment by aeharding** [comment]
Oh, I see! 🤦‍♂️ Thanks for the explanation. Hopefully it will help someone else running into the same issue migrating from lodash.
