### ISSUE TITLE
Get the docs running

### ISSUE THREAD

**Issue by aleclarson** [radashi-org/radashi#40]
We're in the process of migrating the docs away from [Chiller](https://github.com/sodiray/chiller) to use [Starlight by Astro](https://starlight.astro.build/) instead, which should make it easier to support multiple languages (our main priority with the docs).

**Comment by stefaanv** [comment]
Can I assist with this ?

**Comment by aleclarson** [comment]
Appreciate the offer, @stefaanv. All that's left to do is a bit of documentation and a couple small bugs. The site will be up this week. 😄

**Comment by aleclarson** [comment]
The docs are now live at: https://radashi-org.github.io

If you have any ideas about improving Radashi's messaging (e.g. how we pitch Radashi to potential new users), please share your thoughts in [this discussion](https://github.com/orgs/radashi-org/discussions/185).
